### PR TITLE
Store session and refactoring

### PR DESCRIPTION
**Pull request by enwi**
According to [OTAA best practices](https://www.thethingsnetwork.org/docs/devices/bestpractices.html#otaa-best-practices) devices should keep their device address and session, so I added some functionality that these as well as the message up counter are stored and if present upon next join are instead used to directly send messages without having to join.

If I have missed something or needs to be changed, let me know.

Also changed:
- Add NVSHandler for NVS specific code
- Add ByteArrayUtils for byte array specific code
- Merge TTN_esp32 and lorawan_esp32 into TTN_esp32
- Improve instance specific code
- Make variables that should not be accessed by users private and make them available to system callbacks
- Add more code documentation
- Improve code
- Renam joined() to isJoined()

### CODE REVIEW

**Comment by rgot-org** [comment]
Hello Moritz,
I just tested your modifications. However I encounter a problem: the program ttn-otaa.ino reboots permanently (wireless stick). There is an error in NVSHandler.cpp.
```
Rebooting...
Starting
ESP_ERROR_CHECK failed: esp_err_t 0x1102 (ESP_ERR_NVS_NOT_FOUND) at 0x4008ba40
file: "d:\francois\Documents\Arduino\libraries\TheThingsNetwork_esp32-store-session-and-refactoring\src\NVSHandler.cpp" line 78
func: static bool NVSHandler::readNvsValue(HandleCloser&, const char*, uint8_t*, size_t, bool)
expression: result

Backtrace: 0x4008b560:0x3ffb1e80 0x4008ba43:0x3ffb1ea0 0x400d1520:0x3ffb1ec0 0x400d1ead:0x3ffb1ef0 0x400d21ce:0x3ffb1f60 0x400d1276:0x3ffb1f80 0x400d7247:0x3ffb1fb0 0x40088215:0x3ffb1fd0

Rebooting...
```
On the other hand I am not a fan of the `getInstance()` method, this introduces a pointer to the object. Knowing that there will only be one instance, it is easier to instantiate it automatically. I thought this library to be very easy to use (for beginners). If the user must use "`*`", "`->`" and all the pointer rhetoric it is often too complicated.
The idea of saving the session is excellent.
I used 2 files (ttn_esp32 and lorawan_esp32) to separate the junction to TTN and the data backup and what comes under the LMIC stack ( like the [ttn-esp32](https://github.com/manuelbl/ttn-esp32) library for plateformio) but all together in a single file is definitely easier.
Can you look to go back to a "`ttn.`" format instead "`ttn->`" and look at the NVS problem.

Currently I am working to integrate data input using BLE. I have developed a Xamarin application that retrieves data from the device and I can add new ones.

Best regards
François

**Comment by enwi** [comment]
Voilà

**Comment by rgot-org** [comment]
thanks for the reference, 
but i have always the rebooting issue
```
Starting
ESP_ERROR_CHECK failed: esp_err_t 0x1102 (ESP_ERR_NVS_NOT_FOUND) at 0x4008ba40
file: "d:\francois\Documents\Arduino\libraries\TheThingsNetwork_esp32-store-session-and-refactoring\src\NVSHandler.cpp" line 78
func: static bool NVSHandler::readNvsValue(HandleCloser&, const char*, uint8_t*, size_t, bool)
expression: result
```

**Comment by enwi** [comment]
I will fix that tomorrow once and for all :D

**Comment by enwi** [comment]
@rgot-org You can't have the `ESP_ERROR_CHECK failed` error on line 78, as the check has moved, did you update your local code?

**Comment by enwi** [comment]
@rgot-org So this should be it, please test the code and report back to me

**Comment by rgot-org** [comment]
Your code works fine. but i will change how to instantiate the object 
this way is too disappointing for my students.

However great job !
Francois

**Comment by enwi** [comment]
What do you mean by too disappointing?

**Comment by rgot-org** [comment]
my students have difficulty to understand `TTN_esp32& ttn = TTN_esp32::getInstance();`
`TTN_esp32 ttn;  ` is more simple

**Pull request merged**
